// taskus_frontend_angular/src/app/shared/components/dashboard/recent-completed-card/recent-completed-card.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Task } from '../../../../core/models/app.models';

@Component({
  selector: 'app-recent-completed-card',
  standalone: true,
  imports: [CommonModule], // Required for the DatePipe we use in the HTML!
  templateUrl: './recent-completed-card.html',
  styleUrls: ['./recent-completed-card.scss']
})
export class RecentCompletedCard {
  @Input({ required: true }) tasks: Task[] = [];
  @Input() isLoading: boolean = false;

  get recentlyCompleted(): Task[] {
    return this.tasks
      .filter(task => task.status === 'Done' && task.completedAt)
      .sort((a, b) => {
        return new Date(b.completedAt!).getTime() - new Date(a.completedAt!).getTime();
      })
      .slice(0, 3);
  }
}

// taskus_frontend_react/src/components/dashboard/RecentCompletedCard.tsx
import { Task } from '@/types';

interface RecentCompletedCardProps {
  tasks: Task[];
  isLoading: boolean;
}

export const RecentCompletedCard = ({ tasks, isLoading }: RecentCompletedCardProps) => {
  const recentlyCompleted = tasks
    .filter(task => task.status === 'Done' && task.completedAt)
    .sort((a, b) => new Date(b.completedAt!).getTime() - new Date(a.completedAt!).getTime())
    .slice(0, 3);
  return (
    <div className="bg-background rounded-lg p-4 border-2 border-border">
      <h3 className="text-lg font-semibold text-foreground mb-4">
        Recently Completed
      </h3>
      
      {isLoading ? (
        <p className="text-muted-foreground text-sm">Loading...</p>
      ) : recentlyCompleted.length === 0 ? (
        <p className="text-muted-foreground text-sm">No completed tasks yet.</p>
      ) : (
        <div className="space-y-2">
          {recentlyCompleted.map(task => (
            <div key={task.id} className="pb-2 border-b border-border last:border-0">
              <p className="text-sm font-medium text-foreground">{task.title}</p>
              <p className="text-xs text-muted-foreground">
                {new Date(task.completedAt!).toLocaleDateString()}
              </p>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};
