// taskus_frontend_react/src/components/dashboard/TaskCalendar.tsx
import FullCalendar from "@fullcalendar/react";
import dayGridPlugin from "@fullcalendar/daygrid";
import { EventClickArg, EventContentArg } from "@fullcalendar/core";
import { Task } from "@/types";

interface TaskCalendarProps {
  tasks: Task[];
  onTaskClick: (task: Task) => void;
}

export const TaskCalendar = ({ tasks, onTaskClick }: TaskCalendarProps) => {
  const events = tasks
    .filter((task): task is Task & { deadline: string } => !!task.deadline)
    .map((task) => ({
      id: task.id,
      title: task.title,
      date: task.deadline,
      extendedProps: { task },
    }));

  const renderEventContent = ({ event }: EventContentArg) => {
    const task = event.extendedProps.task as Task;
    const statusColor =
      task.status === "Done"
        ? "bg-status-done"
        : task.status === "InProgress"
        ? "bg-status-progress"
        : "bg-status-pending";
    return (
      <div className="flex items-center gap-1 text-[10px] w-full overflow-hidden">
        <span className={`w-2 h-2 rounded-full flex-shrink-0 ${statusColor}`} />
        <span className="truncate w-full">{event.title}</span>
      </div>
    );
  };

  const handleEventClick = (info: EventClickArg) => {
    const task = info.event.extendedProps.task as Task;
    onTaskClick(task);
  };

  return (
    <div className="bg-background rounded-lg border-2 border-border p-4">
      <FullCalendar
        plugins={[dayGridPlugin]}
        initialView="dayGridMonth"
        events={events}
        height="auto"
        displayEventTime={false}
        buttonText={{ today: "Today" }}
        eventClick={handleEventClick}
        eventClassNames="cursor-pointer text-[10px] px-1 py-0.5"
        eventContent={renderEventContent}
      />
    </div>
  );
};

// taskus_frontend_angular/src/app/shared/components/dashboard/task-calendar/task-calendar.ts
import { Component, Input, Output, EventEmitter, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FullCalendarModule } from '@fullcalendar/angular';
import { CalendarOptions, EventClickArg, EventContentArg } from '@fullcalendar/core';
import dayGridPlugin from '@fullcalendar/daygrid';
import { Task } from '../../../../core/models/app.models';

@Component({
  selector: 'app-task-calendar',
  standalone: true,
  imports: [CommonModule, FullCalendarModule],
  templateUrl: './task-calendar.html',
  styleUrls: ['./task-calendar.scss']
})
export class TaskCalendar implements OnChanges {
  @Input({ required: true }) tasks: Task[] = [];
  @Output() taskClick = new EventEmitter<Task>();

  calendarOptions: CalendarOptions = {
    plugins: [dayGridPlugin],
    initialView: 'dayGridMonth',
    height: 'auto',
    displayEventTime: false,
    buttonText: { today: 'Today' },
    eventClick: this.handleEventClick.bind(this),
    eventContent: this.renderEventContent.bind(this),
    events: [] // will be populated in ngOnChanges
  };

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['tasks'] && this.tasks) {
      this.updateEvents();
    }
  }

  updateEvents(): void {
    const calendarEvents = this.tasks
      .filter(task => !!task.deadline)
      .map(task => ({
        id: task.id,
        title: task.title,
        date: task.deadline!,
        extendedProps: { task }
      }));

    // Reassigning the object triggers Angular's change detection to update the UI
    this.calendarOptions = {
      ...this.calendarOptions,
      events: calendarEvents
    };
  }

  renderEventContent(info: EventContentArg) {
    const task = info.event.extendedProps['task'] as Task;
    
    // Determine status class
    let statusClass = 'status-pending';
    if (task.status === 'Done') statusClass = 'status-done';
    else if (task.status === 'InProgress') statusClass = 'status-progress';

    // The "Gotcha": Returning a raw HTML string instead of JSX
    return {
      html: `
        <div class="calendar-event-custom">
          <span class="event-dot ${statusClass}"></span>
          <span class="event-title">${info.event.title}</span>
        </div>
      `
    };
  }

  handleEventClick(info: EventClickArg): void {
    const task = info.event.extendedProps['task'] as Task;
    this.taskClick.emit(task);
  }
}
