// taskus_frontend_react/src/pages/admin/UserManagementScreen.tsx
import { useState, useEffect } from "react";
import { UserPlus } from "lucide-react";
import { AuthorizedLayout } from '@/components/layout/AuthorizedLayout';
import { userService } from "@/services/api";
import { User, UserRequest } from "@/types";
import { toast } from "sonner";
import { UserCard } from "@/components/user/UserCard";
import { UserRequestCard } from "@/components/user/UserRequestCard";

type Tab = "users" | "requests";

export const UserManagementScreen = () => {
  const [activeTab, setActiveTab] = useState<Tab>("users");
  const [users, setUsers] = useState<User[]>([]);
  const [requests, setRequests] = useState<UserRequest[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    try {
      setIsLoading(true);
      const [usersData, requestsData] = await Promise.all([
        userService.getAllUsers(),
        userService.getAllUserRequests(),
      ]);
      setUsers(usersData);
      setRequests(requestsData);
    } catch (error) {
      console.error("Error fetching data:", error);
      toast.error("Failed to load user data");
    } finally {
      setIsLoading(false);
    }
  };

  const handleAcceptRequest = async (requestId: string) => {
    try {
      await userService.acceptUserRequest(requestId);
      toast.success("User request accepted");
      fetchData();
    } catch (error) {
      console.error("Error accepting request:", error);
      toast.error("Failed to accept request");
    }
  };

  const handleRejectRequest = async (requestId: string) => {
    const confirmed = window.confirm("Are you sure you want to reject this request?");
    if (!confirmed) return;

    try {
      await userService.rejectUserRequest(requestId);
      toast.success("User request rejected");
      fetchData();
    } catch (error) {
      console.error("Error rejecting request:", error);
      toast.error("Failed to reject request");
    }
  };

  return (
    <AuthorizedLayout title="User Management">
      <div className="space-y-6">
        {/* Tab Toggle */}
        <div className="flex justify-center">
          <div className="bg-muted p-1 rounded-full inline-flex gap-1">
            <button
              onClick={() => setActiveTab("users")}
              className={`px-6 py-2 rounded-full font-medium transition-all ${
                activeTab === "users"
                  ? "bg-background text-primary shadow-sm"
                  : "text-muted-foreground hover:text-foreground"
              }`}
            >
              Users
              <span className="ml-2 text-sm opacity-75">({users.length})</span>
            </button>
            <button
              onClick={() => setActiveTab("requests")}
              className={`px-6 py-2 rounded-full font-medium transition-all ${
                activeTab === "requests"
                  ? "bg-background text-primary shadow-sm"
                  : "text-muted-foreground hover:text-foreground"
              }`}
            >
              Requests
              <span className="ml-2 text-sm opacity-75">({requests.length})</span>
            </button>
          </div>
        </div>

        {/* Content */}
        {isLoading ? (
          <div className="text-center py-12 text-muted-foreground">
            Loading...
          </div>
        ) : activeTab === "users" ? (
          <div className="space-y-3">
            {users.length === 0 ? (
              <div className="text-center py-12 bg-background rounded-lg border-2 border-border">
                <p className="text-muted-foreground">No users found</p>
              </div>
            ) : (
              users.map((user) => (
                <UserCard key={user.id} user={user} onDelete={fetchData} />
              ))
            )}
          </div>
        ) : (
          <div className="space-y-3">
            {requests.length === 0 ? (
              <div className="text-center py-12 bg-background rounded-lg border-2 border-border">
                <UserPlus className="h-12 w-12 mx-auto mb-4 text-muted-foreground/50" />
                <p className="text-muted-foreground">No pending requests</p>
              </div>
            ) : (
              requests.map((request) => (
                <UserRequestCard
                  key={request.id}
                  request={request}
                  onAccept={handleAcceptRequest}
                  onReject={handleRejectRequest}
                  onDelete={fetchData}
                />
              ))
            )}
          </div>
        )}
      </div>
    </AuthorizedLayout>
  );
};

// taskus_frontend_angular/src/app/pages/admin/user-management-screen/user-management-screen.ts
import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatIconModule } from '@angular/material/icon';
import { toast } from 'ngx-sonner';

import { User, UserRequest } from '../../../core/models/app.models';
import { UserService } from '../../../core/services/user';

import { AuthorizedLayout } from '../../../shared/components/layout/authorized-layout/authorized-layout';
import { UserCard } from '../../../shared/components/user/user-card/user-card';
import { UserRequestCard } from '../../../shared/components/user/user-request-card/user-request-card';

type Tab = 'users' | 'requests';

@Component({
  selector: 'app-user-management-screen',
  standalone: true,
  imports: [
    CommonModule, 
    MatIconModule, 
    AuthorizedLayout, 
    UserCard, 
    UserRequestCard
  ],
  templateUrl: './user-management-screen.html',
  styleUrls: ['./user-management-screen.scss']
})
export class UserManagementScreen implements OnInit {
  activeTab: Tab = 'users';
  users: User[] = [];
  requests: UserRequest[] = [];
  isLoading = true;

  constructor(
    private userService: UserService,
    private cdr: ChangeDetectorRef
  ) {}

  ngOnInit(): void {
    this.fetchData();
  }

  fetchData(): void {
    this.isLoading = true;

    Promise.all([
      this.userService.getAllUsers().toPromise(),
      this.userService.getAllUserRequests().toPromise()
    ]).then(([usersData, requestsData]) => {
      if (usersData) this.users = usersData;
      if (requestsData) this.requests = requestsData;
      this.isLoading = false;
      this.cdr.detectChanges();
    }).catch(error => {
      console.error('Error fetching data:', error);
      toast.error('Failed to load user data');
      this.isLoading = false;
      this.cdr.detectChanges();
    });
  }

  setActiveTab(tab: Tab): void {
    this.activeTab = tab;
  }

  handleAcceptRequest(requestId: string): void {
    this.userService.acceptUserRequest(requestId).subscribe({
      next: () => {
        toast.success('User request accepted');
        this.fetchData();
      },
      error: (error) => {
        console.error('Error accepting request:', error);
        toast.error('Failed to accept request');
      }
    });
  }

  handleRejectRequest(requestId: string): void {
    const confirmed = window.confirm('Are you sure you want to reject this request?');
    if (!confirmed) return;

    this.userService.rejectUserRequest(requestId).subscribe({
      next: () => {
        toast.success('User request rejected');
        this.fetchData();
      },
      error: (error) => {
        console.error('Error rejecting request:', error);
        toast.error('Failed to reject request');
      }
    });
  }
}
